### ISSUE TITLE
Code syntax highlighting

### ISSUE THREAD

**Issue by samholmes** [0phoff/MDXP#6]
Looks like syntax-highlighting isn't supported. In my presentation.mdx file I added the ` ```ts ` and the code block isn't highlighted with TypesScript syntax highlighting. I tried other languages as well.

**Comment by 0phoff** [comment]
Yes, syntax highlighting is not provided by default, though you can probably use [@theme-ui/prism](https://theme-ui.com/guides/syntax-highlighting/) in order to enable it.

Not everyone wants syntax highlighting in their presentations and adding it is not too difficult, so this is not a priority for me to work on.

**Comment by tonai** [comment]
I could not find a compatible package for `@theme-ui/prism`.
When installing `@theme-ui/prism` with `npm i @theme-ui/prism` I have the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mdxp@1.0.0
npm ERR! Found: theme-ui@0.3.5
npm ERR! node_modules/theme-ui
npm ERR!   theme-ui@"^0.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer theme-ui@"^0.11" from @theme-ui/prism@0.13.1
npm ERR! node_modules/@theme-ui/prism
npm ERR!   @theme-ui/prism@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/tocab/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tocab/.npm/_logs/2022-01-06T17_04_26_071Z-debug.log
```
But even after changing the version of `theme-ui` in `package.json` it still fails because of peerDependencies of `theme-ui` that are declared in `@mdxp/core`, `@mdxp/components`...etc. (In `@mdxp/core` There is a peerDependency: "theme-ui": "^0.3.1")

I tryied installing `@theme-ui/prism` with older version but I could not find a version that match the one requested by  `@mdxp/core`... :/
